name: CustomBlockBreak
version: ${project.version}
main: me.gilan.customblockbreak.Main
authors: [Gilan]
description: Allows Certain blocks to change form or not break when broken by not oped players.
